### ISSUE TITLE
Update API library and use Common API

### ISSUE THREAD

**Issue by leoj3n** [feathersjs-ecosystem/feathers-twilio#10]
This service is using an outdated version of the Twilio API library. I've looked a little bit into the new API, but I'm really not sure how to update this service to be compatible with the Feathers Common API, so I'm collecting some perhaps useful information here in hopes someone else might take a look.

### Twilio API docs

- [New Twilio API](https://www.twilio.com/docs/libraries/node)
- [Old API vs New API](https://support.twilio.com/hc/en-us/articles/223181028-Switching-from-SMS-Messages-resource-URI-to-Messages-resource-URI-)

### Twilio Paging Information docs

- [Link to "Paging Information"](https://www.twilio.com/docs/usage/twilios-response#response-formats-list-paging-information)

![image](https://user-images.githubusercontent.com/990216/49412560-777e6e00-f732-11e8-9129-a418750e09b7.png)

### Twilio messages stream docs

- [Link to "Read: List messages matching filter criteria"](https://www.twilio.com/docs/sms/api/message-resource?code-sample=code-read-list-all-messages&code-language=Node.js&code-sdk-version=3.x#example-2-2)

![image](https://user-images.githubusercontent.com/990216/49412617-abf22a00-f732-11e8-890d-9cf05ad00347.png)

Twilio's API library repository docs showing how to use `this.list`:

- [List messages using callbacks or promises](https://github.com/twilio/twilio-node/blob/61d5e82d1cf40db07577efddb550a48c3e3bf2d9/examples/example.js#L116-L131)

`this.list` uses `this.each` internally:

- [`this.list` source code](https://github.com/twilio/twilio-node/blob/61d5e82d1cf40db07577efddb550a48c3e3bf2d9/lib/rest/messaging/v1/service.js#L225-L276)
- [`this.each` source code](https://github.com/twilio/twilio-node/blob/61d5e82d1cf40db07577efddb550a48c3e3bf2d9/lib/rest/messaging/v1/service.js#L135-L222)

### Pseudo code for `sms.js`

Here I'm trying to handle pagination based off the mongoose service and what Twilio supports:

- [Mongoose service code](https://github.com/feathersjs-ecosystem/feathers-mongoose/blob/e23ecf101d1028b2a668616dee82f5a771b0e42c/lib/service.js#L40-L124)
- [Twilio messaging service code](https://github.com/twilio/twilio-node/blob/master/lib/rest/messaging/v1/service.js#L135-L222)

```js
class Service {
  constructor (options = {}) {
    if (!options.accountSid) {
      throw new Error('Twilio `accountSid` needs to be provided');
    }

    if (!options.authToken) {
      throw new Error('Twilio `authToken` needs to be provided');
    }

    this.from = options.from || null;
    this.paginate = options.paginate || {};
    
    const twilio = new Twilio(options.accountSid, options.authToken);
    this.client = twilio.messages;
  }

  find (params) {
    const paginate = (params && typeof params.paginate !== 'undefined') ? params.paginate : this.paginate;
    const result = this._find(params, !!paginate.default,
      query => filterQuery(query, paginate)
    );

    return result;
  }

  _find (params, count, getFilter = filterQuery) {
    const { filters, query } = getFilter(params.query || {});

    let opts = {};

    if (count) {
      // Handle $limit
      if (typeof filters.$limit !== 'undefined') {
        opts = {
          limit: filters.$limit,
          pageSize: this.paginate.max
        }; 
      } else {
        opts = {
          limit: this.paginate.default,
          pageSize: this.paginate.max
        };
      }
    }

    return new Promise((resolve, reject) => {
      return this.client.list(opts).then(resolve).catch(reject);
    });
  }

// Note: I'm really not sure about this code or how to connect Twilio to Feathers.
```

### Feathers pagination:

I'm not sure to what extent this idea of pagination can be supported?

- [Feathers pagination docs](https://docs.feathersjs.com/api/databases/common#pagination)
- [Feathers querying docs](https://github.com/feathersjs/docs/blob/master/api/databases/querying.md)

Seeing as the new Twilio API is "streaming" I don't know how that changes things.

### `statusCallback`

Users might want to be able to pass extra options like a `statusCallback` URL:

- [Monitor the status of your message](https://www.twilio.com/docs/sms/send-messages?code-sample=code-send-an-sms-with-a-statuscallback-url&code-language=Node.js&code-sdk-version=3.x#monitor-the-status-of-your-message)

EDIT:

- https://www.twilio.com/engineering/2015/04/16/replacing-absolute-paging-with-relative-paging

**Comment by daffl** [comment]
That's why we didn't do that I think. Not sure if it's worth the effort of mapping in between the syntax when the easiest way would be to just pass the query through. You'd like not expose this service directly.

**Comment by leoj3n** [comment]
Okay, so you will accept a PR passing through but not patching the API to do what Common API expects? Would it make sense to raise the issue with Twilio and say we wan them to be compatible with Common API?

**Comment by daffl** [comment]
Yes, a PR that just passes the API calls through will be fine. I'm not sure if Twilio would be interested in making this change. Since it's not really a database, I don't think it's super important for the syntax to match.

**Comment by leoj3n** [comment]
I'm going to make the simplest update possible that doesn't unnecessarily change or add any functionality. However, I'm wondering about how this project would be developed further. What would make sense to add, and did @ekryski have any specific ideas when he wrote this:

https://github.com/feathersjs-ecosystem/feathers-twilio/blob/52fe29eb7bc9546321744e7b941523bfd9ad801d/src/services/sms.js#L21

When I was thinking about matching the common API as best as possible, I had `find` returning an object with `total`, `limit` and a `data` array. I also made use of the Twilio `usage` API to handle `$limit=0` (the alternative is to [count manually](https://stackoverflow.com/questions/35974501/twilio-api-count-messages-number-has-received)), or passed along any non-zero `limit` to the Twilio library, which accepts a limit parameter. Is this what @ekryski was thinking of doing with params and pagination, or did he mean something else?

However, the Twilio API doesn't really support traditional pagination:

https://www.twilio.com/engineering/2015/04/16/replacing-absolute-paging-with-relative-paging

So, what could @ekryski have done with pagination?

**Comment by leoj3n** [comment]
See #11 for the simple update.
